### ISSUE TITLE
SensirionShdlcTxFrame: In begin() why is _index not set to 0? 

### ISSUE THREAD

**Issue by Guswib** [Sensirion/arduino-core#9]
Is there a reason why ìn the class SensirionShdlcTxFrame, the begin() function does not set the _index variable to 0?

As the _index is only set to 0 when the SensirionShdlcTxFrame is initialized and is private, it is not possible to make SensirionShdlcTxFrame global and reusable, which means I have to create new instantce everytime I want to use SensirionShdlcTxFrame. 
As the protocol only seem to allow one frame at the time to be sent, I dont see the reason why begin does not set _index to 0 in the begin function.

**Comment by sdmueller** [comment]
Hi @Guswib 

I don't think there is a specific reason for why the index does not get set to 0.
It was just not designed with reusability in mind.

You are however very welcome to create a pull request to make it reusable.

**Comment by Guswib** [comment]
Just did a pull request
